name: Node.js CI

on:
  workflow_dispatch:
  
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - run: npm ci
    

      
    - name: Commit built files
      run: |
        git checkout -b dist
        git add dist/
        git commit -m "Update dist"
        git push origin dist
